name: "Setup ToolR"
description: "Install ToolR via uvx and cache it"
author: "Pedro Algarvio"

inputs:
  version:
    description: ToolR version to install
    default: "${{ github.action_ref }}"

outputs:
  version:
    description: ToolR version installed
    value: ${{ steps.install-toolr.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Cache key suffix — ensures different versions don't clobber each other
        cache-suffix: toolr-${{ inputs.version }}
        activate-environment: true

    - name: Install ToolR
      shell: bash
      id: install-toolr
      run: |
        ACTION_VERSION_TAG=${{ github.action_ref }}
        VERSION_FROM_TAG=${ACTION_VERSION_TAG#v}
        if [ "${VERSION_FROM_TAG}" = "latest" ]; then
          TOOLR_VERSION=$(uvx toolr --version)
        else
          TOOLR_VERSION=$(uvx toolr==${VERSION_FROM_TAG} --version)
        fi
        echo "version=$TOOLR_VERSION" >> "$GITHUB_OUTPUT"
