name: "Setup ToolR"
description: "Install ToolR via uvx and cache it"
author: "Pedro Algarvio"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # Cache key suffix — ensures different versions don't clobber each other
        cache-suffix: toolr-${{ github.ref_name }}

    - name: Determine ToolR version
      id: version
      shell: bash
      run: |
        if [[ "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "TOOLR_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        else
          echo "TOOLR_VERSION=latest" >> $GITHUB_ENV
        fi

    - name: Install ToolR
      shell: bash
      run: |
        if [ "$TOOLR_VERSION" = "latest" ]; then
          uvx toolr --version
        else
          uvx toolr==${TOOLR_VERSION} --version
        fi
