name: "Setup ToolR"
description: "Install ToolR via uvx and cache it"
author: "Pedro Algarvio"

inputs:
  version:
    description: ToolR version to install
    default: "${{ github.ref_name }}"

outputs:
  version:
    description: ToolR version installed
    value: ${{ steps.install-toolr.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Cache key suffix — ensures different versions don't clobber each other
        cache-suffix: toolr-${{ inputs.version }}

    - name: Install ToolR
      shell: bash
      id: install-toolr
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          TOOLR_VERSION=$(uvx toolr --version)
        else
          TOOLR_VERSION=$(uvx toolr==${{ inputs.version }} --version)
        fi
        echo "version=$TOOLR_VERSION" >> "$GITHUB_OUTPUT"
