site_name: ToolR Documentation
strict: true
theme:
  name: material
  logo: imgs/toolr.png
  icon: imgs/toolr.png
  favicon: imgs/toolr.png
  palette:
    primary: black
    accent: indigo
    scheme: slate

  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow

docs_dir: docs
site_dir: site


# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

plugins:
  - autorefs:
      resolve_closest: true
  - search
  - awesome-nav
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: [python]
          options:
            allow_inspection: true
            show_source: true
            find_stubs_package: true
            members_order: source
            separate_signature: true
            #filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://rich.readthedocs.io/en/stable/objects.inv

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      separator: "-"
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - markdown_include.include:
      base_path: .

watch:
  - python
  - docs
