//! Tab-time manifest freshness logic.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::discovery::discover_project_root;
use crate::manifest::{Manifest, Origin, load_manifest};
use crate::parser::build_static_manifest;

/// Outcome of resolving the manifest for a completion request.
#[derive(Debug)]
pub struct ResolvedManifest {
    pub manifest: Manifest,
    /// `true` if the cached on-disk manifest was returned verbatim
    /// (both `static_hash` and `third_party_hash` matched the live state).
    pub from_cache: bool,
    /// The directory that contained `tools/` (the project root).
    pub project_root: PathBuf,
}

/// Resolve the manifest to serve for a completion request rooted at
/// `cwd`. Walks up to find `tools/`, delegates freshness checking to
/// [`crate::freshness::compare`], and either returns the cached manifest
/// verbatim or re-parses and returns a fresh one (with any dynamic-layer
/// and third-party entries from the cache preserved).
pub fn resolve_manifest_at_tab(cwd: &Path) -> Result<ResolvedManifest> {
    let project_root = discover_project_root(cwd)
        .with_context(|| format!("walking up from {} to find tools/", cwd.display()))?;
    let tools_dir = project_root.join("tools");
    let manifest_path = tools_dir.join(".toolr-manifest.json");
    let cached = load_manifest(&manifest_path).ok();

    // Tab completion never globs the venv — too costly on the hot path.
    // Passing `venv_dir = None` to `compare` skips the third-party axis
    // entirely; the cached third_party_hash is treated as canonical and
    // only static drift triggers a re-parse. Real third-party changes will
    // be picked up on the next dispatch invocation, which does pass the
    // venv path.
    let verdict = crate::freshness::compare(cached.as_ref(), &tools_dir, None)?;

    if matches!(verdict, crate::freshness::FreshnessVerdict::Fresh) {
        // compare() returns Fresh only when cached is Some.
        let cached = cached.expect("Fresh verdict requires a cached manifest");
        return Ok(ResolvedManifest {
            manifest: cached,
            from_cache: true,
            project_root,
        });
    }

    // StaticDrift (or ThirdPartyDrift, which tab completion treats the
    // same way): re-parse `tools/*.py` and preserve cached dynamic +
    // third-party entries that wouldn't be regenerated by the static
    // pass.
    let mut fresh = build_static_manifest(&tools_dir)?;
    if let Some(cached) = cached {
        preserve_non_static_entries(&mut fresh, cached);
    }

    Ok(ResolvedManifest {
        manifest: fresh,
        from_cache: false,
        project_root,
    })
}

/// Carry forward non-`Static` (i.e. `ThirdParty`) entries from the cache
/// that don't collide with anything the fresh static parser produced.
/// Also stamps the cached `third_party_hash` onto the fresh manifest,
/// since we didn't re-glob.
///
/// **NOTE:** This helper is safe for tab completion's in-memory use only.
/// Callers that persist the resulting manifest (e.g. dispatch's
/// `ensure_manifest_fresh`) MUST recompute `third_party_hash` from the
/// live venv after calling this, otherwise stale hashes will persist
/// across invocations.
fn preserve_non_static_entries(fresh: &mut Manifest, cached: Manifest) {
    for group in cached.groups {
        if !matches!(group.origin, Origin::Static)
            && !fresh.groups.iter().any(|g| g.name == group.name)
        {
            fresh.groups.push(group);
        }
    }
    for cmd in cached.commands {
        if !matches!(cmd.origin, Origin::Static)
            && !fresh
                .commands
                .iter()
                .any(|c| c.group == cmd.group && c.name == cmd.name)
        {
            fresh.commands.push(cmd);
        }
    }
    fresh.third_party_hash = cached.third_party_hash;
}
