name: Apply Release Patch
description: Prepare a release of ToolR

inputs:
  release-patch-name:
    required: true
    description: 'Release patch to apply'


runs:
  using: composite

  steps:

    - name: Download Release Patch Artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: ${{ inputs.release-patch-name }}

    - name: Apply The Release Patch
      shell: bash
      run: |
        git am --committer-date-is-author-date ${{ inputs.release-patch-name }}
