//! Generators for the `toolr-command-authoring` skill.
//!
//! Two files are produced:
//!
//! - `references/commands.md` — the inventory of every name in
//!   `toolr.__all__`, rendered from the AST of the file each name
//!   resolves to via the package-root re-export walk.
//! - `references/docstrings.md` — the Google-style docstring conventions
//!   toolr's parser accepts, rendered from
//!   [`toolr_core::docstrings::KNOWN_SECTION_HEADERS`].
//!
//! Both generators are byte-stable: sorted iteration throughout, no
//! timestamps, LF line endings, exactly one trailing newline.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use ruff_python_ast::{Expr, ModModule, Stmt};
use ruff_text_size::Ranged;
use toolr_core::docstrings::KNOWN_SECTION_HEADERS;

use super::Generated;

const DO_NOT_EDIT: &str =
    "<!-- generated by `cargo xtask build-skill-refs`; do not edit by hand -->";

/// Path (under `repo_root`) of the toolr-py package root.
const TOOLR_PY_ROOT: &str = "crates/toolr-py/python";

/// Path (under `repo_root`) of the file the `__all__` walk starts from.
const TOOLR_PKG_INIT: &str = "crates/toolr-py/python/toolr/__init__.py";

/// Build the `references/commands.md` file for the authoring skill.
pub fn commands(repo_root: &Path) -> Result<Generated> {
    let (init_source, init_module) = parse_with_source(&repo_root.join(TOOLR_PKG_INIT))?;
    let all_names = read_all_list(&init_module, &init_source)
        .context("reading toolr.__all__ from crates/toolr-py/python/toolr/__init__.py")?;
    let init_imports = read_from_imports(&init_module, &init_source);

    let mut entries: Vec<Entry> = Vec::new();
    for name in &all_names {
        entries.push(resolve_entry(name, repo_root, &init_imports, &init_source, &init_module)?);
    }
    // ASCII sort by name for stable output, irrespective of __all__'s
    // declared order.
    entries.sort_by(|a, b| a.name.cmp(&b.name));

    let body = render_commands(&entries);
    Ok(Generated {
        path: repo_root
            .join("skills/toolr-command-authoring/references/commands.md"),
        body,
    })
}

/// Build the `references/docstrings.md` file for the authoring skill.
pub fn docstrings(repo_root: &Path) -> Result<Generated> {
    // Group headers by category so the reference reads naturally
    // ("here are the headers that mean Args:, here are the ones that
    // mean Examples:, ..."). Inside each group, headers are emitted in
    // KNOWN_SECTION_HEADERS' order (already ASCII-sorted by header
    // spelling).
    let mut by_category: BTreeMap<&'static str, Vec<&'static str>> = BTreeMap::new();
    for (header, category) in KNOWN_SECTION_HEADERS {
        by_category.entry(*category).or_default().push(*header);
    }

    let mut body = String::new();
    body.push_str("# Toolr docstring conventions\n\n");
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str(
        "Toolr parses Google-style docstrings on every command and group. The \
        parser lives in `crates/toolr-core/src/docstrings.rs` and drives the \
        `--help` output your users see. This reference is generated from the \
        same `KNOWN_SECTION_HEADERS` table the parser reads at runtime, so \
        the conventions documented here are the conventions the parser \
        recognises — they cannot drift.\n\n",
    );

    body.push_str("## Structure\n\n");
    body.push_str(
        "- The **first non-empty line** of the docstring becomes the command's \
        short help — the one-liner shown in the parent group's `--help` \
        listing.\n",
    );
    body.push_str(
        "- Body text before the first section header becomes the long \
        description shown on `<command> --help`.\n",
    );
    body.push_str(
        "- An `Args:` section (also accepts `Arguments:` / `Parameters:`, \
        case-insensitive) provides per-parameter help in the form \
        `name: description`.\n",
    );
    body.push_str(
        "- An `Examples:` section is rendered in the long help via \
        [termimad](https://github.com/Canop/termimad); fenced code blocks \
        and `>>>` doctest blocks both work.\n",
    );
    body.push_str(
        "- Section detection is **case-insensitive**: `Args:`, `ARGS:`, and \
        `args:` are all equivalent.\n\n",
    );

    body.push_str("## Recognised section headers\n\n");
    body.push_str(
        "Each header below is matched against the start of a trimmed, \
        lowercased line. Headers ending in `:` match the standalone section \
        form (`Args:`); headers ending in a space match the inline form \
        (`Attr foo:`).\n\n",
    );

    body.push_str("| Category | Recognised headers |\n");
    body.push_str("| --- | --- |\n");
    for (category, headers) in &by_category {
        let cells: Vec<String> = headers
            .iter()
            .map(|h| {
                // Headers ending in a space are inline forms; render
                // with a `<name>` placeholder so the trailing space
                // doesn't get swallowed by markdown linters and the
                // intended usage is clear.
                if let Some(prefix) = h.strip_suffix(' ') {
                    format!("`{prefix} <name>`")
                } else {
                    format!("`{h}`")
                }
            })
            .collect();
        let _ = writeln!(body, "| `{category}` | {} |", cells.join(", "));
    }

    body.push('\n');
    body.push_str(
        "Categories `returns`, `yields`, `raises`, `attributes`, and `attr` \
        are detected by the parser but currently ignored when rendering \
        help. They are listed above so you know they will not raise \
        \"unknown section\" errors; use them freely.\n",
    );

    Ok(Generated {
        path: repo_root
            .join("skills/toolr-command-authoring/references/docstrings.md"),
        body,
    })
}

// --- AST helpers ------------------------------------------------------------

/// Read a Python file from disk and return the source text alongside
/// the parsed AST. The source is kept so we can slice it via the
/// [`ruff_python_ast::Ranged`]-style TextRange offsets the parser
/// attaches to each node.
fn parse_with_source(path: &Path) -> Result<(String, ModModule)> {
    let source = std::fs::read_to_string(path)
        .with_context(|| format!("reading {}", path.display()))?;
    let parsed = ruff_python_parser::parse_module(&source)
        .with_context(|| format!("parsing {}", path.display()))?;
    Ok((source, parsed.into_syntax()))
}

/// Slice the source by an AST node's TextRange. Used to extract the
/// exact source spelling of signatures, defaults, and annotations —
/// rather than re-printing via the AST, which normalises formatting.
fn slice_source<R: Ranged>(source: &str, node: &R) -> String {
    let range = node.range();
    let start: usize = range.start().to_usize();
    let end: usize = range.end().to_usize();
    source[start..end].to_string()
}

/// Read the module-level `__all__ = [...]` assignment and extract its
/// string-literal entries. Errors loudly if `__all__` is missing,
/// shadowed, or contains a non-string element — the spec says we do
/// not fall back to scanning imports.
fn read_all_list(module: &ModModule, source: &str) -> Result<Vec<String>> {
    let mut value: Option<&Expr> = None;
    for stmt in &module.body {
        let Stmt::Assign(assign) = stmt else { continue };
        if assign.targets.len() != 1 {
            continue;
        }
        let Expr::Name(name) = &assign.targets[0] else {
            continue;
        };
        if name.id.as_str() == "__all__" {
            value = Some(&assign.value);
        }
    }

    let list = match value {
        Some(Expr::List(list)) => list,
        Some(other) => {
            return Err(anyhow!(
                "toolr.__all__ is not a list literal (got {})",
                slice_source(source, other),
            ));
        }
        None => return Err(anyhow!("toolr.__all__ not found")),
    };

    let mut names = Vec::with_capacity(list.elts.len());
    for elt in &list.elts {
        if let Expr::StringLiteral(s) = elt {
            names.push(s.value.to_str().to_string());
        } else {
            return Err(anyhow!(
                "toolr.__all__ contains a non-string entry: {}",
                slice_source(source, elt),
            ));
        }
    }
    Ok(names)
}

/// Map each name imported in the module via `from X import Y` to its
/// dotted source module path. Plain `import X` is ignored — toolr-py's
/// `__init__.py` only re-exports via the `from … import …` shape, and
/// that is the contract the spec promises to handle.
fn read_from_imports(module: &ModModule, _source: &str) -> BTreeMap<String, String> {
    let mut imports = BTreeMap::new();
    for stmt in &module.body {
        if let Stmt::ImportFrom(import_from) = stmt {
            let Some(module_name) = &import_from.module else {
                continue;
            };
            for alias in &import_from.names {
                let local = alias
                    .asname
                    .as_ref()
                    .map(|n| n.as_str())
                    .unwrap_or(alias.name.as_str());
                imports.insert(local.to_string(), module_name.as_str().to_string());
            }
        }
    }
    imports
}

/// Translate a dotted Python module path (e.g. `toolr.utils._signature`)
/// to the on-disk file we should parse, rooted at `crates/toolr-py/python`.
/// Falls back to the package's `__init__.py` if a `name.py` doesn't exist.
fn module_to_path(repo_root: &Path, module: &str) -> PathBuf {
    let rel: PathBuf = module.split('.').collect();
    let py_root = repo_root.join(TOOLR_PY_ROOT);
    let direct = py_root.join(&rel).with_extension("py");
    if direct.exists() {
        direct
    } else {
        py_root.join(&rel).join("__init__.py")
    }
}

/// One reference entry. The renderer turns this into a `## <name>`
/// section in `commands.md`.
struct Entry {
    name: String,
    kind: EntryKind,
    source_module: String,
    signature: Option<String>,
    docstring: Option<String>,
}

enum EntryKind {
    Function,
    Class,
    Constant,
    Special, // e.g. `__version__` — derived at import time.
}

fn resolve_entry(
    name: &str,
    repo_root: &Path,
    init_imports: &BTreeMap<String, String>,
    init_source: &str,
    init_module: &ModModule,
) -> Result<Entry> {
    if name == "__version__" {
        return Ok(Entry {
            name: name.to_string(),
            kind: EntryKind::Special,
            source_module: "toolr".to_string(),
            signature: Some("__version__: str".to_string()),
            docstring: Some(
                "Installed toolr-py package version, resolved at import time \
                 via `importlib.metadata.version(\"toolr-py\")`."
                    .to_string(),
            ),
        });
    }

    // Start at the package root. If the name is imported from a
    // sub-module, follow the re-export chain through every
    // intermediate `__init__.py` until we hit a file that defines the
    // name directly. The chain is bounded to a small depth to surface
    // cycles or unexpected layouts as a build error rather than an
    // infinite loop.
    let mut current_module = "toolr".to_string();
    let mut current_source = init_source.to_string();
    let mut current_ast: ModModule = clone_module(init_module);
    let mut current_imports = init_imports.clone();

    for _ in 0..8 {
        if let Some(stmt) = find_definition(&current_ast, name) {
            return render_entry(name, &current_module, &current_source, stmt);
        }
        let Some(next_module) = current_imports.get(name).cloned() else {
            return Err(anyhow!(
                "name `{name}` from toolr.__all__ is not imported and not \
                 defined in `{current_module}` — check toolr.__all__ vs the \
                 source module",
            ));
        };
        let path = module_to_path(repo_root, &next_module);
        let (next_source, next_ast) = parse_with_source(&path)?;
        current_imports = read_from_imports(&next_ast, &next_source);
        current_module = next_module;
        current_source = next_source;
        current_ast = next_ast;
    }

    Err(anyhow!(
        "re-export walk for `{name}` exceeded depth 8 — suspected cycle or \
         deeply nested re-export chain",
    ))
}

/// Cheap deep-clone of a ModModule body. The walker mutates the
/// "current" module as it follows re-exports; rather than tracking
/// lifetimes through a recursive walk, we keep the previous module
/// owned and replace it wholesale.
fn clone_module(module: &ModModule) -> ModModule {
    ModModule {
        node_index: module.node_index.clone(),
        range: module.range,
        body: module.body.clone(),
    }
}

fn find_definition<'a>(module: &'a ModModule, name: &str) -> Option<&'a Stmt> {
    for stmt in &module.body {
        match stmt {
            Stmt::FunctionDef(def) if def.name.as_str() == name => return Some(stmt),
            Stmt::ClassDef(def) if def.name.as_str() == name => return Some(stmt),
            Stmt::Assign(assign) if assign.targets.len() == 1 => match &assign.targets[0] {
                Expr::Name(n) if n.id.as_str() == name => return Some(stmt),
                _ => {}
            },
            Stmt::AnnAssign(assign) => match assign.target.as_ref() {
                Expr::Name(n) if n.id.as_str() == name => return Some(stmt),
                _ => {}
            },
            _ => {}
        }
    }
    None
}

fn render_entry(
    name: &str,
    source_module: &str,
    source: &str,
    stmt: &Stmt,
) -> Result<Entry> {
    let (kind, signature, docstring) = match stmt {
        Stmt::FunctionDef(def) => {
            let sig = function_signature(def, source);
            let doc = function_docstring(&def.body);
            (EntryKind::Function, Some(sig), doc)
        }
        Stmt::ClassDef(def) => {
            let sig = format!("class {}", def.name.as_str());
            let doc = function_docstring(&def.body);
            (EntryKind::Class, Some(sig), doc)
        }
        Stmt::AnnAssign(assign) => {
            let sig = slice_source(source, assign);
            (EntryKind::Constant, Some(sig), None)
        }
        Stmt::Assign(assign) => {
            let sig = slice_source(source, assign);
            (EntryKind::Constant, Some(sig), None)
        }
        other => {
            return Err(anyhow!(
                "unhandled definition shape for `{name}`: {}",
                slice_source(source, other),
            ));
        }
    };
    Ok(Entry {
        name: name.to_string(),
        kind,
        source_module: source_module.to_string(),
        signature,
        docstring,
    })
}

/// Render a `def` signature as `def name(...)` using the source text of
/// the parameter list (so default values, annotations, and `*`/`**`
/// markers come out the same way the author spelled them).
fn function_signature(def: &ruff_python_ast::StmtFunctionDef, source: &str) -> String {
    let header_end = def
        .body
        .first()
        .map(|s| s.range().start().to_usize())
        .unwrap_or_else(|| def.range().end().to_usize());
    let header_start = def.range().start().to_usize();
    let header = &source[header_start..header_end];
    // Trim everything from the trailing colon onwards (signature only).
    if let Some(colon_idx) = header.rfind(':') {
        let mut sig = header[..colon_idx].to_string();
        // Collapse internal newlines + indentation so multi-line
        // signatures fit a single code block line per parameter via
        // dedent-and-rewrap. We keep newlines (helps readability) but
        // strip common leading indentation so the output is anchored
        // at column zero.
        sig = dedent(&sig);
        sig.push(':');
        sig
    } else {
        header.trim_end().to_string()
    }
}

fn dedent(input: &str) -> String {
    let lines: Vec<&str> = input.lines().collect();
    let min_indent = lines
        .iter()
        .skip(1) // first line is at "def" column already
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);
    let mut out = String::new();
    for (i, line) in lines.iter().enumerate() {
        if i == 0 {
            out.push_str(line);
        } else {
            out.push('\n');
            if line.len() >= min_indent {
                out.push_str(&line[min_indent..]);
            } else {
                out.push_str(line.trim_start());
            }
        }
    }
    out
}

fn function_docstring(body: &[Stmt]) -> Option<String> {
    let first = body.first()?;
    let Stmt::Expr(expr_stmt) = first else {
        return None;
    };
    let Expr::StringLiteral(lit) = expr_stmt.value.as_ref() else {
        return None;
    };
    Some(lit.value.to_str().to_string())
}

// --- Markdown rendering -----------------------------------------------------

fn render_commands(entries: &[Entry]) -> String {
    let mut out = String::new();
    out.push_str("# Toolr command-authoring reference: API surface\n\n");
    out.push_str(DO_NOT_EDIT);
    out.push_str("\n\n");
    out.push_str(
        "Every name exposed by `import toolr` is documented below. The list \
        is generated from `toolr.__all__`; each entry is rendered from the \
        source file the package root re-exports it from. If a name you \
        expect to see isn't here, add it to `toolr.__all__` and \
        regenerate.\n\n",
    );
    out.push_str("## Importable surface\n\n");
    out.push_str("```python\n");
    out.push_str("from toolr import (\n");
    for entry in entries {
        let _ = writeln!(out, "    {},", entry.name);
    }
    out.push_str(")\n");
    out.push_str("```\n\n");
    out.push_str("## Entries\n\n");
    for entry in entries {
        render_entry_md(&mut out, entry);
    }
    // Normalise trailing whitespace + EOF.
    let mut trimmed = out.trim_end().to_string();
    trimmed.push('\n');
    trimmed
}

fn render_entry_md(out: &mut String, entry: &Entry) {
    let kind = match entry.kind {
        EntryKind::Function => "function",
        EntryKind::Class => "class",
        EntryKind::Constant => "constant",
        EntryKind::Special => "special",
    };
    let _ = writeln!(out, "### `{}`\n", entry.name);
    let _ = writeln!(
        out,
        "**Kind:** {kind} &nbsp;·&nbsp; **Source:** `{}`\n",
        entry.source_module
    );
    if let Some(sig) = &entry.signature {
        out.push_str("```python\n");
        out.push_str(sig.trim_end());
        out.push('\n');
        out.push_str("```\n\n");
    }
    if let Some(doc) = &entry.docstring {
        out.push_str(&render_docstring_block(doc));
        out.push('\n');
    } else {
        out.push_str(
            "_No docstring on the source definition._\n\n",
        );
    }
}

/// Render a docstring as a fenced text block. Indentation in the
/// original docstring is normalised (textwrap.dedent equivalent) so
/// long, multi-line docs render predictably regardless of how deep
/// the source definition was nested. A fenced block (not a
/// blockquote) is used because docstrings frequently embed indented
/// `Args:` lines and example code; the `>` quote prefix would
/// trigger markdown-linter MD027 ("multiple spaces after quote
/// marker") on those lines.
fn render_docstring_block(doc: &str) -> String {
    let lines: Vec<&str> = doc.lines().collect();
    let min_indent = lines
        .iter()
        .skip(1)
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);
    let mut out = String::new();
    out.push_str("```text\n");
    for (i, line) in lines.iter().enumerate() {
        let stripped = if i == 0 {
            line.trim_start()
        } else if line.len() >= min_indent {
            &line[min_indent..]
        } else {
            line.trim_start()
        };
        let _ = writeln!(out, "{stripped}");
    }
    out.push_str("```\n");
    out
}
