//! Generator for the `toolr-ci-setup` skill's `references/action.md`.
//!
//! Source of truth is the repo-root `action.yml`. The generator
//! parses the action's `name`, `description`, `inputs`, and
//! `outputs` tables and renders them as markdown so an agent reading
//! the skill sees the action surface without having to read raw YAML.

use std::fmt::Write;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Deserialize;

use super::Generated;

const DO_NOT_EDIT: &str =
    "<!-- generated by `cargo xtask build-skill-refs`; do not edit by hand -->";

#[derive(Deserialize)]
struct Action {
    name: String,
    description: String,
    #[serde(default)]
    inputs: indexmap::IndexMap<String, Input>,
    #[serde(default)]
    outputs: indexmap::IndexMap<String, Output>,
}

#[derive(Deserialize)]
struct Input {
    #[serde(default)]
    description: String,
    #[serde(default)]
    default: Option<String>,
}

#[derive(Deserialize)]
struct Output {
    #[serde(default)]
    description: String,
}

pub fn action(repo_root: &Path) -> Result<Generated> {
    let yaml_path = repo_root.join("action.yml");
    let yaml = std::fs::read_to_string(&yaml_path)
        .with_context(|| format!("reading {}", yaml_path.display()))?;
    let body = render(&yaml).with_context(|| {
        format!("rendering action surface from {}", yaml_path.display())
    })?;
    Ok(Generated {
        path: repo_root.join("skills/toolr-ci-setup/references/action.md"),
        body,
    })
}

fn render(yaml: &str) -> Result<String> {
    let action: Action =
        serde_yaml_ng::from_str(yaml).context("parsing action.yml as YAML")?;
    let mut body = String::new();
    body.push_str("# `s0undt3ch/ToolR` action surface\n\n");
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str("Generated from the repository-root `action.yml`.\n\n");

    writeln!(body, "## Name and description\n").unwrap();
    writeln!(
        body,
        "**{}** — {}\n",
        action.name,
        collapse(&action.description)
    )
    .unwrap();

    writeln!(body, "## Inputs\n").unwrap();
    if action.inputs.is_empty() {
        writeln!(body, "_(none declared)_\n").unwrap();
    } else {
        writeln!(body, "| Name | Default | Description |").unwrap();
        writeln!(body, "| ---- | ------- | ----------- |").unwrap();
        for (name, input) in &action.inputs {
            let default = match input.default.as_deref() {
                None | Some("") => "_(empty)_".to_string(),
                Some(value) => format!("`{value}`"),
            };
            writeln!(
                body,
                "| `{name}` | {default} | {} |",
                collapse(&input.description)
            )
            .unwrap();
        }
        body.push('\n');
    }

    writeln!(body, "## Outputs\n").unwrap();
    if action.outputs.is_empty() {
        writeln!(body, "_(none declared)_").unwrap();
    } else {
        writeln!(body, "| Name | Description |").unwrap();
        writeln!(body, "| ---- | ----------- |").unwrap();
        for (name, output) in &action.outputs {
            writeln!(
                body,
                "| `{name}` | {} |",
                collapse(&output.description)
            )
            .unwrap();
        }
    }

    Ok(body)
}

/// Collapse a multi-line YAML scalar into a single line suitable for
/// a markdown table cell: newlines become spaces, runs of whitespace
/// collapse to one, the result is trimmed.
fn collapse(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_space = false;
    for ch in s.chars() {
        if ch.is_whitespace() {
            if !prev_space && !out.is_empty() {
                out.push(' ');
            }
            prev_space = true;
        } else {
            out.push(ch);
            prev_space = false;
        }
    }
    out.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE: &str = r#"
name: "Setup ToolR"
description: |
  Install the ToolR Rust binary from a GitHub release and
  verify its SLSA build provenance.

inputs:
  version:
    description: |
      ToolR version to install.
    default: ""
  skip-attestation:
    description: "Skip gh attestation verify."
    default: "false"

outputs:
  version:
    description: Resolved ToolR version installed (no leading `v`).
"#;

    #[test]
    fn renders_name_description_inputs_and_outputs() {
        let out = render(FIXTURE).expect("render should succeed");
        let expected = "# `s0undt3ch/ToolR` action surface\n\n\
            <!-- generated by `cargo xtask build-skill-refs`; do not edit by hand -->\n\n\
            Generated from the repository-root `action.yml`.\n\n\
            ## Name and description\n\n\
            **Setup ToolR** — Install the ToolR Rust binary from a GitHub release and verify its SLSA build provenance.\n\n\
            ## Inputs\n\n\
            | Name | Default | Description |\n\
            | ---- | ------- | ----------- |\n\
            | `version` | _(empty)_ | ToolR version to install. |\n\
            | `skip-attestation` | `false` | Skip gh attestation verify. |\n\n\
            ## Outputs\n\n\
            | Name | Description |\n\
            | ---- | ----------- |\n\
            | `version` | Resolved ToolR version installed (no leading `v`). |\n";
        assert_eq!(out, expected);
    }

    #[test]
    fn empty_default_renders_as_empty_marker() {
        let yaml = "name: t\ndescription: t\ninputs:\n  a:\n    description: x\n";
        let out = render(yaml).expect("render should succeed");
        assert!(out.contains("| `a` | _(empty)_ | x |"));
    }

    #[test]
    fn collapse_normalises_whitespace() {
        assert_eq!(collapse("foo\n  bar\n\tbaz"), "foo bar baz");
        assert_eq!(collapse("  trim me  "), "trim me");
        assert_eq!(collapse(""), "");
    }
}
