//! Generator for the `toolr-command-packaging` skill's
//! `references/packaging.md`.
//!
//! Source of truth is the Rust serde types under `toolr-core`. Rather
//! than hand-rolling a JSON schema (and watching it rot), the generator
//! embeds the relevant Rust source verbatim via `include_str!` and
//! extracts named regions delimited by `// region: <Tag>` /
//! `// endregion: <Tag>` markers in the source files.
//!
//! Adding a new section: bracket the relevant type with markers in the
//! source file, then add an entry to [`SECTIONS`].

use std::fmt::Write;
use std::path::Path;

use anyhow::{Result, anyhow};

use super::Generated;

const DO_NOT_EDIT: &str =
    "<!-- generated by `cargo xtask build-skill-refs`; do not edit by hand -->";

/// Rust source files whose region markers feed the packaging reference.
const MANIFEST_MODEL: &str =
    include_str!("../../../toolr-core/src/manifest/model.rs");
const FRAGMENT_MODEL: &str =
    include_str!("../../../toolr-core/src/third_party/model.rs");
const GLOB_MODULE: &str =
    include_str!("../../../toolr-core/src/third_party/glob.rs");

/// A `## <heading>` section of the rendered reference. Each section
/// pairs hand-written narrative with a verbatim Rust extract.
struct Section {
    heading: &'static str,
    /// Markdown body — should be written so it reads naturally with a
    /// trailing fenced rust block appended.
    narrative: &'static str,
    /// `(file, tag)` for the region the generator should extract and
    /// append after the narrative.
    source: (&'static str, &'static str),
}

const SECTIONS: &[Section] = &[
    Section {
        heading: "Schema version",
        narrative: "`FRAGMENT_SCHEMA_VERSION` is the version your \
                    plugin's `toolr-manifest.json` declares via the \
                    mandatory `toolr_schema_version` field. The toolr \
                    binary accepts fragments at this version or lower, \
                    applying migrations as needed; fragments at a \
                    higher version are rejected.",
        source: ("third_party/model.rs", "SkillRefFragmentVersion"),
    },
    Section {
        heading: "Fragment shape",
        narrative: "The fragment is the JSON blob your plugin ships at \
                    `<pkg>/toolr-manifest.json` inside the installed \
                    wheel. Fields default to empty where reasonable so \
                    a plugin can ship just `groups` or just `commands` \
                    without padding the file.",
        source: ("third_party/model.rs", "SkillRefManifestFragment"),
    },
    Section {
        heading: "Origin",
        narrative: "Once merged into the project's manifest, every \
                    group and command carries an `origin` field. \
                    Plugins always end up tagged `\"third_party\"`. \
                    You never set this yourself — the merger does. \
                    Listed here so you can recognise plugin-origin \
                    entries when inspecting `tools/.toolr-manifest.json`.",
        source: ("manifest/model.rs", "SkillRefOrigin"),
    },
    Section {
        heading: "Top-level project manifest (for context)",
        narrative: "Your fragment is merged into the project's own \
                    `tools/.toolr-manifest.json`. The host shape is \
                    listed here so you can see where your data lands. \
                    `third_party_hash` is computed by toolr over the \
                    sorted set of discovered fragments; you do not \
                    write it.",
        source: ("manifest/model.rs", "SkillRefManifest"),
    },
    Section {
        heading: "Plugin manifest schema (host invariants)",
        narrative: "Host-side schema version the merger expects on the \
                    project's own manifest. Bumped in lockstep with \
                    breaking changes to the host format; plugins don't \
                    need to react to it directly because their fragment \
                    is migrated to the latest before merge.",
        source: ("manifest/model.rs", "SkillRefSchemaVersion"),
    },
];

pub fn packaging(repo_root: &Path) -> Result<Generated> {
    let mut body = String::new();
    body.push_str("# Toolr command-packaging reference: plugin manifest\n\n");
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str(
        "This reference is generated from `toolr-core`'s own types. The \
        struct definitions below are extracted verbatim from \
        `crates/toolr-core/src/manifest/model.rs` and \
        `crates/toolr-core/src/third_party/model.rs`. If you ship a \
        plugin whose `toolr-manifest.json` matches the schema below, \
        toolr's loader will accept it. If you ship one that doesn't, \
        the load will fail with a clear error from \
        `parse_fragment`.\n\n",
    );

    body.push_str("## Discovery\n\n");
    body.push_str(
        "Toolr discovers your plugin by globbing every installed \
        wheel's package root for a file named `toolr-manifest.json`. \
        The exact globbing pattern is in \
        `crates/toolr-core/src/third_party/glob.rs`:\n\n",
    );
    body.push_str("```text\n");
    body.push_str(&glob_summary());
    body.push_str("```\n\n");
    body.push_str(
        "Either layout works on every supported platform. If your \
        wheel installs `<pkg>/toolr-manifest.json` next to the \
        package's `__init__.py`, the glob picks it up.\n\n",
    );

    for section in SECTIONS {
        let extract = extract_region(section.source.0, section.source.1)?;
        let _ = writeln!(body, "## {}\n", section.heading);
        body.push_str(section.narrative);
        body.push_str("\n\n");
        body.push_str("```rust\n");
        body.push_str(&extract);
        body.push_str("```\n\n");
    }

    // Trim trailing whitespace + ensure exactly one trailing newline.
    let mut trimmed = body.trim_end().to_string();
    trimmed.push('\n');

    Ok(Generated {
        path: repo_root
            .join("skills/toolr-command-packaging/references/packaging.md"),
        body: trimmed,
    })
}

fn extract_region(file: &str, tag: &str) -> Result<String> {
    let source = match file {
        "manifest/model.rs" => MANIFEST_MODEL,
        "third_party/model.rs" => FRAGMENT_MODEL,
        other => {
            return Err(anyhow!(
                "build_skill_refs::packaging: no embedded copy of `{other}` \
                 — add an `include_str!` entry above SECTIONS",
            ));
        }
    };
    let start_marker = format!("// region: {tag}");
    let end_marker = format!("// endregion: {tag}");

    let start = source
        .find(&start_marker)
        .ok_or_else(|| anyhow!("missing `{start_marker}` in {file}"))?;
    // Step past the start marker line.
    let after_start = source[start..]
        .find('\n')
        .map(|n| start + n + 1)
        .ok_or_else(|| anyhow!("malformed start marker in {file}"))?;
    let end = source[after_start..]
        .find(&end_marker)
        .map(|n| after_start + n)
        .ok_or_else(|| anyhow!("missing `{end_marker}` in {file} (after {tag} start)"))?;

    // Drop the blank line we'd otherwise leave between the last item
    // and the endregion marker. Trim once, append a single newline.
    let mut extract = source[after_start..end].trim_end().to_string();
    extract.push('\n');
    Ok(extract)
}

fn glob_summary() -> String {
    // Pull the first few lines of the module doc so the reference text
    // matches what the source itself documents.
    let mut lines = Vec::new();
    for line in GLOB_MODULE.lines() {
        if let Some(stripped) = line.strip_prefix("//! ") {
            lines.push(stripped.to_string());
        } else if line == "//!" {
            lines.push(String::new());
        } else if !line.is_empty() {
            break;
        }
    }
    // Trim trailing blank lines.
    while matches!(lines.last(), Some(s) if s.is_empty()) {
        lines.pop();
    }
    let mut joined = lines.join("\n");
    joined.push('\n');
    joined
}
