//! Generators that ship a named docs section straight inside a skill,
//! via [`docs_section::extract`], so the skill reads it without mkdocs
//! or a live link back to `docs/`.
//!
//! Adding one: pick a `(doc_rel, section)` pair already marked in the
//! docs with `--8<-- [start:<name>]` / `[end:<name>]`, then add an
//! entry below.

use std::path::Path;

use anyhow::{Context, Result};

use super::Generated;
use super::docs_section;

const DO_NOT_EDIT: &str =
    "<!-- generated by `cargo xtask build-skill-refs`; do not edit by hand -->";
const DO_NOT_EDIT_TOML: &str =
    "# generated by `cargo xtask build-skill-refs`; do not edit by hand";

/// Render one section-backed reference: a `# <title>` line, the
/// `DO_NOT_EDIT` marker, a provenance sentence naming the doc and
/// section, then the extracted body.
fn render(repo_root: &Path, doc_rel: &str, section: &str, title: &str) -> Result<String> {
    let extracted = docs_section::extract(repo_root, doc_rel, section)
        .with_context(|| format!("extracting `{section}` from {doc_rel}"))?;
    let mut body = String::new();
    body.push_str(&format!("# {title}\n\n"));
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str(&format!(
        "Extracted from {doc_rel} in the toolr repository (section `{section}`).\n\n"
    ));
    body.push_str(&extracted);
    Ok(body)
}

/// Build `skills/toolr-command-authoring/references/arguments.md` from
/// `docs/writing-commands/arguments.md`'s `arg-shapes` section.
pub fn arguments_reference(repo_root: &Path) -> Result<Generated> {
    let body = render(
        repo_root,
        "docs/writing-commands/arguments.md",
        "arg-shapes",
        "Argument shapes",
    )?;
    Ok(Generated {
        path: repo_root.join("skills/toolr-command-authoring/references/arguments.md"),
        body,
    })
}

/// Build the `prek-hook.md` reference for both the `toolr-ci-setup`
/// and `toolr-command-packaging` skills, from `docs/third-party.md`'s
/// `prek-hook` section.
pub fn prek_hook_references(repo_root: &Path) -> Result<Vec<Generated>> {
    let body = render(
        repo_root,
        "docs/third-party.md",
        "prek-hook",
        "Keeping the manifest fresh with a prek hook",
    )?;
    Ok(vec![
        Generated {
            path: repo_root.join("skills/toolr-ci-setup/references/prek-hook.md"),
            body: body.clone(),
        },
        Generated {
            path: repo_root.join("skills/toolr-command-packaging/references/prek-hook.md"),
            body,
        },
    ])
}

/// Copy the reference plugin's `pyproject.toml` into the packaging
/// skill so the skill doesn't need a live link into the repo tree.
pub fn packaging_example(repo_root: &Path) -> Result<Generated> {
    let source = repo_root.join("examples/plugin-package/pyproject.toml");
    let content = std::fs::read_to_string(&source)
        .with_context(|| format!("reading {}", source.display()))?;
    let mut body = String::new();
    body.push_str(DO_NOT_EDIT_TOML);
    body.push('\n');
    body.push_str(&content);
    Ok(Generated {
        path: repo_root.join("skills/toolr-command-packaging/examples/pyproject.toml"),
        body,
    })
}
