//! Generators for the supported-type and path-constraint catalogues,
//! shared by `references/types.md` and the two docs snippets so the
//! skill and the docs can't drift from each other.

use std::fmt::Write;
use std::path::Path;

use anyhow::Result;
use toolr_core::parser::types::{PathConstraintDoc, PathConstraints, SupportedType, TypeDoc};

use super::Generated;

const DO_NOT_EDIT: &str =
    "<!-- generated by `cargo xtask build-skill-refs`; do not edit by hand -->";

/// Escape `|` so it survives inside a markdown table cell.
fn escape_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

/// Render one row's annotation cell: the annotation wrapped in a code
/// span (with `|` escaped inside it too), followed by the note (if
/// any) as plain text after one space.
fn render_annotation_cell(doc: &TypeDoc) -> String {
    let annotation = escape_cell(doc.annotation);
    if doc.note.is_empty() {
        format!("`{annotation}`")
    } else {
        format!("`{annotation}` {}", doc.note)
    }
}

/// The `| Annotation | Validated by | Wire format | Python receives |`
/// table shared by `references/types.md` and
/// `docs/writing-commands/files/supported-types.md`.
fn render_types_table() -> String {
    let mut out = String::new();
    out.push_str("| Annotation | Validated by | Wire format | Python receives |\n");
    out.push_str("|---|---|---|---|\n");
    for doc in SupportedType::catalogue() {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            render_annotation_cell(&doc),
            escape_cell(doc.validated_by),
            escape_cell(doc.wire_format),
            escape_cell(doc.python_receives),
        );
    }
    out
}

/// The `| Constraint | Effect |` table shared by `references/types.md`
/// and `docs/writing-commands/files/path-constraints.md`.
fn render_path_table() -> String {
    let mut out = String::new();
    out.push_str("| Constraint | Effect |\n");
    out.push_str("|---|---|\n");
    for doc in PathConstraints::catalogue() {
        let PathConstraintDoc { keyword, effect } = doc;
        let _ = writeln!(out, "| `arg({keyword}=True)` | {} |", escape_cell(effect));
    }
    out
}

/// Sentence linking the path-constraint table to the types it applies to.
const PATH_CONSTRAINT_APPLIES_TO: &str = "Apply them with \
`Annotated[Path, arg(must_be_file=True)]`; they apply to `pathlib.Path`, \
`toolr.types.AbsolutePath` and `toolr.types.ResolvedPath`.";

/// Build `skills/toolr-command-authoring/references/types.md`.
pub fn types_reference(repo_root: &Path) -> Result<Generated> {
    let mut body = String::new();
    body.push_str("# Supported argument types\n\n");
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str(
        "Toolr enforces a closed set of parameter types. Anything outside this set is \
         rejected at manifest-build time. Richer types come from the `toolr.types` \
         namespace; each one is a stdlib alias at runtime.\n\n",
    );

    body.push_str("## Types\n\n");
    body.push_str(&render_types_table());
    body.push('\n');

    body.push_str("## Path constraints\n\n");
    body.push_str(&render_path_table());
    body.push('\n');
    body.push_str(PATH_CONSTRAINT_APPLIES_TO);
    body.push('\n');

    Ok(Generated {
        path: repo_root.join("skills/toolr-command-authoring/references/types.md"),
        body,
    })
}

/// Build `docs/writing-commands/files/supported-types.md`.
pub fn supported_types_snippet(repo_root: &Path) -> Result<Generated> {
    let mut body = String::new();
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str(&render_types_table());

    Ok(Generated {
        path: repo_root.join("docs/writing-commands/files/supported-types.md"),
        body,
    })
}

/// Build `docs/writing-commands/files/path-constraints.md`.
pub fn path_constraints_snippet(repo_root: &Path) -> Result<Generated> {
    let mut body = String::new();
    body.push_str(DO_NOT_EDIT);
    body.push_str("\n\n");
    body.push_str(&render_path_table());

    Ok(Generated {
        path: repo_root.join("docs/writing-commands/files/path-constraints.md"),
        body,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escape_cell_escapes_pipes() {
        assert_eq!(escape_cell("T | None"), "T \\| None");
    }

    #[test]
    fn render_annotation_cell_wraps_bare_annotation() {
        let doc = TypeDoc {
            annotation: "int",
            validated_by: "clap",
            wire_format: "JSON number",
            python_receives: "`int`",
            note: "",
        };
        assert_eq!(render_annotation_cell(&doc), "`int`");
    }

    #[test]
    fn render_annotation_cell_appends_note_after_one_space() {
        let doc = TypeDoc {
            annotation: "Enum",
            validated_by: "clap (member values)",
            wire_format: "string",
            python_receives: "enum member",
            note: "subclass",
        };
        assert_eq!(render_annotation_cell(&doc), "`Enum` subclass");
    }

    #[test]
    fn render_annotation_cell_escapes_pipe_inside_code_span() {
        let doc = TypeDoc {
            annotation: "T | None",
            validated_by: "clap (`required=false`)",
            wire_format: "typed or absent",
            python_receives: "`T` or `None`",
            note: "",
        };
        assert_eq!(render_annotation_cell(&doc), "`T \\| None`");
    }

    #[test]
    fn types_table_has_one_row_per_catalogue_entry() {
        let table = render_types_table();
        assert_eq!(table.lines().count(), 2 + SupportedType::catalogue().len());
    }

    #[test]
    fn path_table_uses_real_arg_keywords() {
        let table = render_path_table();
        assert!(table.contains("`arg(must_exist=True)`"));
        assert!(table.contains("`arg(must_be_file=True)`"));
        assert!(table.contains("`arg(must_be_dir=True)`"));
        assert!(!table.contains("path_must_"));
    }
}
