name: setup-pre-commit
description: Setup 'pre-commit'

inputs:
  version:
    description: Prek version to install
    default: "0.2.3"
  cache-seed:
    description: Cache seed to use for prek
    required: true
    default: prek-action
  rust-toolchain:
    required: true
    description: Rust toolchain to install
    default: stable
  rust-components:
    required: true
    description: Rust components to install
    default: clippy,rustfmt

outputs:
  prek-version:
    description: Prek version installed
    value: ${{ steps.install-prek.outputs.prek-version }}
  prek-home:
    description: Prek home directory
    value: ${{ steps.setup-prek-home.outputs.prek-home }}

runs:
  using: composite

  steps:

    - name: Get Python version checksum
      id: python-version-checksum
      shell: bash
      run: |
        VERSION_SHA256SUM=$(python --version --version | sha256sum | cut -d ' ' -f 1)
        echo "VERSION_SHA256SUM=$VERSION_SHA256SUM"
        echo "version-sha256sum=$VERSION_SHA256SUM" >> "$GITHUB_OUTPUT"
        echo "python-path=$(which python)" >> "$GITHUB_OUTPUT"

    - name: Install prek
      id: install-prek
      uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1.0.11
      with:
        install-only: true

    - name: Setup prek home
      shell: bash
      id: setup-prek-home
      run: |
        PREK_HOME=${{ github.workspace }}/.cache/prek
        echo "prek-home=${PREK_HOME}" >> "$GITHUB_OUTPUT"
        echo "PREK_HOME=${PREK_HOME}" >> "$GITHUB_ENV"
        echo "PREK_COLOR=always" >> "$GITHUB_ENV"

    - name: Cache MyPy & Ruff Caches
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ${{ github.workspace }}/.mypy_cache
          ${{ github.workspace }}/.ruff_cache
        key: |-
          mypy-ruff-cache|${{ inputs.cache-seed }}|${{ runner.os }}|${{ runner.arch }}|${{
            steps.install-prek.outputs.prek-version }}|${{
            steps.python-version-checksum.outputs.version-sha256sum }}|${{
            hashFiles('pyproject.toml') }}|${{
            hashFiles(format('{0}/**/.pre-commit-config.yaml', github.workspace))
          }}

    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      with:
        cache-key: prek|${{ inputs.cache-seed }}
        toolchain: ${{ inputs.rust-toolchain }}
        components: ${{ inputs.rust-components }}

    - name: Set up prek hooks cache
      id: cache-prek-hooks
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.setup-prek-home.outputs.prek-home }}
        key: |-
          prek-home|${{ inputs.cache-seed }}|${{ runner.os }}|${{ runner.arch }}|${{
            steps.install-prek.outputs.prek-version }}|${{
            steps.python-version-checksum.outputs.version-sha256sum }}|${{
            hashFiles(format('{0}/**/.pre-commit-config.yaml', github.workspace))
          }}

    - name: Install prek hooks
      shell: bash
      if: ${{ steps.cache-prek-hooks.outputs.cache-hit != 'true' }}
      run: |
        prek install --install-hooks
