name: Throttle Build
description: Throttle the build to avoid thundering herd effects.

inputs:
  max-sleep-seconds:
    description: The maximum number of seconds to sleep.
    required: true
    default: '15'

runs:
  using: composite

  steps:
    - name: Configure Git
      shell: bash
      env:
        MAX_SLEEP: ${{ inputs.max-sleep-seconds }}
      run: |
        t=$(python3 -c 'import os, random, sys; sys.stdout.write(str(random.randint(1, int(os.environ["MAX_SLEEP"]))))'); echo "Sleeping $t seconds"; sleep "$t"
