name: Build macOS

on:
  workflow_call:
    inputs:
      display-name:
        required: true
        type: string
        description: 'Display name for the build job'
      release-patch-name:
        required: true
        type: string
        description: 'Release patch to apply'

jobs:
  build:
    name: ${{ inputs.display-name }} (${{ matrix.python-version }}, ${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
        arch:
          - "x86_64"
          - "aarch64"
        # This creates 6 parallel builds: 3 Python versions × 2 architectures

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Apply Release Patch
        uses: ./.github/actions/apply-release-patch
        with:
          release-patch-name: ${{ inputs.release-patch-name }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-cargo-${{ matrix.python-version }}-${{ matrix.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install `cibuildwheel`
        run: |
          pip install cibuildwheel

      - name: Install Rust target for macOS cross-compilation
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Build wheels
        env:
          CIBW_PLATFORM: macos
          # Convert aarch64 to arm64 for macOS (cibuildwheel convention)
          CIBW_ARCHS: ${{ matrix.arch == 'aarch64' && 'arm64' || matrix.arch }}
          CIBW_BUILD: ${{ matrix.python-version == '3.11' && 'cp311*' || matrix.python-version == '3.12' && 'cp312*' || 'cp313*' }}
        run: |
          echo "Building for Python ${{ matrix.python-version }} on ${{ matrix.arch }}"
          echo "CIBW_BUILD=$CIBW_BUILD"
          echo "CIBW_ARCHS=$CIBW_ARCHS"
          cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v4
        with:
          name: dist-macos-${{ matrix.python-version }}-${{ matrix.arch }}
          path: dist
